dataset_path:
raw_dataset_path: /home/liang/GTA/data/halfcheetah-medium-expert-v2.pkl
aug_dataset_path: /home/liang/vgks-full/data/aug/halfcheetah-medium-expert-v2/halfcheetah-medium-expert-seed0.pkl
mix_aug_ratio: 0.1
aug_take_topq: true
env: halfcheetah-medium-expert-v2
seed: 0
device: cuda:0
GDA: None
eval_freq: 5000
n_episodes: 10
max_timesteps: 1000000
checkpoints_path: checkpoints/td3bc_base
save_checkpoints: true
log_every: 1000
load_model: ""
project: halfcheetah-medium-expert-v2
group: TD3_BC-D4RL
name: TD3_BC_BASE
buffer_size: 10000000
batch_size: 256
discount: 0.99
expl_noise: 0.1
tau: 0.005
policy_noise: 0.2
noise_clip: 0.5
policy_freq: 2
alpha: 2.5
normalize: true
normalize_reward: false
network_width: 256
network_depth: 2
